version: '3.8'

services:
  database:
    image: mysql:8.0
    container_name: recette_project-database
    environment:
      MYSQL_DATABASE: recette_db
      MYSQL_USER: recette_user
      MYSQL_PASSWORD: recette_password
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "3308:3306"  # Expose MySQL sur 3308 pour Ã©viter le conflit avec XAMPP
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - recette_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 5

  php:
    build: .
    container_name: recette_project-php
    ports:
      - "8082:80"
    depends_on:
      - database
    volumes:
      - .:/var/www/html
    environment:
      DATABASE_URL: "mysql://recette_user:recette_password@database:3306/recette_db?serverVersion=8.0"
    networks:
      - recette_network

  mailer:
    image: axllent/mailpit
    container_name: recette_project-mailer
    ports:
      - "58309:8025"
      - "58310:1025"
    networks:
      - recette_network

volumes:
  mysql_data:

networks:
  recette_network:
    driver: bridge
