version: '3.8'

services:
    # Service PHP/Symfony
    app:
        build: .
        container_name: recette_project_app
        ports:
            - "8081:80"  # Port local 8081 â†’ port conteneur 80
        environment:
            DATABASE_URL: "mysql://symfony_user:symfony_password@db:3306/recipe"
            APP_ENV: prod
            APP_SECRET: your_secret_key_here
            MAILER_DSN: "smtp://mailer:1025"
        volumes:
            - .:/var/www/html
        depends_on:
            db:
                condition: service_healthy
        networks:
            - compose_network

    # Service MySQL
    db:
        image: mysql:8.0
        container_name: compose_enjoy_db
        environment:
            MYSQL_ROOT_PASSWORD: root_password
            MYSQL_DATABASE: recipe
            MYSQL_USER: symfony_user
            MYSQL_PASSWORD: symfony_password
        ports:
            - "3308:3306"
        volumes:
            - db_data:/var/lib/mysql
        networks:
            - compose_network
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
            interval: 10s
            timeout: 5s
            retries: 5

    # Service Mailer (Mailpit)
    mailer:
        image: axllent/mailpit
        container_name: recette_project_mailer
        ports:
            - "1025:1025"  # SMTP
            - "8025:8025"  # Web UI
        networks:
            - compose_network

volumes:
    db_data:

networks:
    compose_network:
        driver: bridge
