services:
    - type: web
      name: recette-project
      env: docker
      plan: free
      dockerfilePath: ./Dockerfile
      envVars:
          - key: DATABASE_URL
            value: mysql://symfony_user:symfony_password@db:3306/recipe
          - key: APP_ENV
            value: prod
          - key: APP_SECRET
            value: your_secret_key_here
          - key: MAILER_DSN
            value: smtp://mailer:1025

databases:
    - name: recette-project-db
      databaseName: recipe
      user: symfony_user
      ipAllowList: []
