# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    # Les paramètres vont ici
    recipes_upload_dir: '%kernel.project_dir%/public/uploads/recipes'

services:
    # Configuration automatique par défaut
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # Configuration spécifique pour le service d'images
    App\Services\ImageDownloadService:
        arguments:
            $uploadDir: '%recipes_upload_dir%'


    App\Services\RecetteScraperService:
            arguments:
                $entityManager: '@doctrine.orm.entity_manager'
                $parser: '@App\Services\RecetteParserService'

    App\Services\:
        resource: '../src/Services/'
        autowire: true
        autoconfigure: true



    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
